### ISSUE TITLE
Error SSH

### ISSUE THREAD

**Issue by Fanget-Nicolas** [GSGBen/powershell#1]
Hello,

wanting to try SSH on my Raspberry Pi 3, after installing the module and setting the right syntax. An error has occurred:

```
ssh pi@192.168.1.200
bash : Le terme «bash» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, 
ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.
Au caractère C:\Program Files\WindowsPowerShell\Modules\ssh-wrapper\1.0\ssh-wrapper.psm1:17 : 2
+     bash -c "ssh $args"
+     ~~~~
    + CategoryInfo          : ObjectNotFound: (bash:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Can you help me, please?

**Comment by GSGBen** [comment]
I sure can!

This function only wraps the native ssh in Windows Subsystem for Linux - i.e. Ubuntu/Bash on Windows 10. You'll need this installed and working first. Once you can open that and ssh from there, you'll know its working and can use this instead.

![image](https://user-images.githubusercontent.com/15712321/36291250-f3eca24e-131d-11e8-97df-997e02e5aa61.png)

I'll update the documentation to make this a bit clearer.

Commit: https://github.com/GSGBen/powershell/commit/6535809cadcc73128d7e9db83c61844351b38511
